### ISSUE TITLE
Release for Create 0.5.1-f and Fabric Loader 0.16.5?

### ISSUE THREAD

**Issue by gniftygnome** [Shulej/createsifter#2]
We are running a server with Create 0.5.1-f-build.1417+mc1.20.1 and Fabric Loader 0.16.5.  We can't upgrade to Create 0.5.1-j yet because of version conflicts and because 0.5.1-j is still receiving major bugfixes.  I have built this project with the dependencies reduced to the versions above (no source modifications required) and it runs fine (modulo the bug I already reported in the previous issue).  Would you be willing to do a release with looser dependency versions?  I suspect it will be a while before we can make the jump to 0.5.1-j.

**Comment by Shulej** [comment]
Sure, but it will have to wait after holidays as I'm not home rn haha

**Comment by gniftygnome** [comment]
Nothing better than travel.  Enjoy your holidays!  :)

**Comment by Shulej** [comment]
The source was updated, I have already submitted the new build to curseforge. Should be available soon. I'll close this issue once it's uploaded

**Comment by Shulej** [comment]
Build approved. Closing the issue. Have fun playing with the mod!
